#!/bin/bash

{ # prevent script from running if partially downloaded

set -euo pipefail

sudo_prompt() {
  echo "please enter your password for sudo authentication"
  sudo -k
  sudo echo "sudo authentication successful!"
  while true ; do sudo -n true ; sleep 60 ; kill -0 "$$" || exit ; done 2>/dev/null &
}

install_command_line_tools() {
  # unattended installation of Command Line Tools
  xcode-select -p >/dev/null || {
    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    CLT=$( softwareupdate -l |
      grep "\*.*Command Line Tools" |
      head -n 1 |
      awk -F ":" '{print $2}' |
      sed -e 's/^ *//' |
      tr -d '\n' )
    softwareupdate -i "$CLT" --verbose
    rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
  }
  echo "Command Line Tools installed at $(xcode-select -p)"
}

install_nix() {
  command -v nix >/dev/null || {
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  }
  echo "nix installed"
}

install_brew() {
  command -v brew >/dev/null || {
    NONINTERACTIVE=1 /bin/bash -c "$(curl --proto '=https' --tlsv1.2 -sSf -L https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # do I need to add brew to my path somehow for the homebrew home-manager module to work?
    # or is having brew installed at `/opt/homebrew/bin/brew` enough?
  }
  echo "brew installed"
}

clone_repository() {
  grep -q "https://github.com/ollema/dotfiles.git" "${HOME}/dotfiles/.git/config"
  if [[ $? -eq 0 ]]
  then
    cd "${HOME}/dotfiles"
    git status
    cd -
  else
    rm -rf "${HOME}/dotfiles"
    git clone "https://github.com/ollema/dotfiles.git" "${HOME}/dotfiles"
  fi
}

# installation flow
sudo_prompt
install_command_line_tools
install_nix
install_brew
clone_repository

} # prevent script from running if partially downloaded
